export default {
  DETAIL: 'Detail',
  EDIT_PROFILE: 'Editar perfil',
  FILTER: 'Filter',
  LOGIN: 'Login',
  MAP: 'Map',
  MY_LOCATION: 'Mi ubicación',
  MY_PUBLISH: 'Mis publicaciones',
  NEW_PUBLISH: 'Nueva Publicacion',
  PROFILE_LIST: 'Profile List',
  PROFILE: 'Perfil',
  PUBLISH_DETAIL: 'Publish Detail',
  PUBLISH_LIST: 'Publish List',
  PUBLISH: 'Publicar',
  REGISTER: 'Register',
  SEARCH_LIST: 'Buscar en lista',
  SEARCH_MAP: 'Buscar en mapa',
  SEARCH_TAB: 'Search Tab',
  SEARCH: 'Buscar',
  SETTINGS: 'Configuración',
  UPDATE_PUBLISH: 'Actualizar Publicacion',
};
