export default {
  ALERTS_INFO: 'Alerts Information',
  ALERTS_LIST: 'Alerts List',
  ALERTS: 'Alerts',
  DETAIL: 'Detail',
  EDIT_PROFILE: 'Edit Profile',
  FILTER: 'Filter',
  LOGIN: 'Login',
  MAP: 'Map',
  MY_LOCATION: 'My Location',
  MY_PUBLISH: 'My Publish',
  NEW_PUBLISH: 'New Publish',
  PROFILE_LIST: 'Profile List',
  PROFILE: 'Profile',
  PUBLISH_LIST: 'Publish List',
  PUBLISH: 'Publish',
  REGISTER: 'Register',
  SEARCH_LIST: 'Search List',
  SEARCH_MAP: 'Search Map',
  SEARCH_TAB: 'Search Tab',
  SEARCH: 'Search',
  SETTINGS: 'Settings',
};
